<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <script type="text/javascript" src="design/js/jquery/jquery.min.js?<?php echo $design->getStaticHash() ?>"></script>
    <script type="text/javascript" src="design/js/jquery/plugins/mfupload.js?<?php echo $design->getStaticHash() ?>"></script>
    <script type="text/javascript" src="design/js/uploader.js?<?php echo $design->getStaticHash() ?>"></script>
    <script type="text/javascript" src="design/js/script.js?<?php echo $design->getStaticHash() ?>"></script>

    <link type="text/css" rel="stylesheet" href="design/style/style.css?<?php echo $design->getStaticHash() ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="design/style/uploader.css?<?php echo $design->getStaticHash() ?>" media="all" />

    <title>Patch check</title>
</head>
<body>
<br />
    <div id="main_content_div">
        <div id="uploader">
            <div id="upload"></div>
            <div id="uploaded"></div>
        </div>
        <div id="separator">-OR-</div>
        <div id="mqp_form_container">
            <span>Enter MQP Patch ID</span>
            <form id="mqp_form" action="index.php">
                <input id="mqp_input_patch_id" name="patch_id" type="text" value="<?php echo $_GET['patch_id'] ?? '' ?>" placeholder="MDVA-3333">
                <button type="submit">Check</button>
                <span id="mqp_error_patch_id"></span>
            </form>
        </div>
        <div id="results_div">
            <?php if (isset($result['check_results'])): ?>
                <?php foreach($result['check_results'] as $name => $group): ?>
                    <table class="result_table">
                        <thead>
                            <tr>
                                <td colspan="2"><?php echo $name ?></td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($group as $release): ?>
                                <tr>
                                    <?php if ($release['check_result'] === 'n/a'): ?>
                                        <td colspan="3">
                                            <?php echo ($release['release_name'] === 'n/a') ? '&nbsp;' : $release['release_name'] ?>
                                        </td>
                                    <?php else: ?>
                                        <td>
                                            <?php echo $release['release_name'] ?>
                                        </td>
                                        <td class="<?php echo ($release['check_result']) ? 'td_ok' : 'td_fail' ?>">
                                            <?php echo ($release['check_result']) ? 'Ok' : 'No' ?>
                                        </td>
                                        <td class="<?php echo ($release['check_git_result']) ? 'td_git_ok' : 'td_git_fail' ?>">
                                            <?php echo ('a') ?>
                                            <?php echo ($release['check_git_result']) ? 'Ok' : 'No' ?>
                                        </td>
                                    <?php endif; ?>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

        <div id="legend_container_div">
            <div id="legend_header_div">Legend<span id="legend_fold_icon" class="fold_icon"></span></div>
            <div id ="legend_body_div">
                <table class="result_table legend_table">
                    <thead>
                        <tr class="subheader">
                            <td>Status</td>
                            <td>Description</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="td_ok">Ok</td>
                            <td class="description_td">Patch is applicable.</td>
                        </tr>
                        <tr>
                            <td class="td_adaptation_required">No</td>
                            <td class="description_td">
                                Patch failed to apply by specific apply strategy, however it was successfully applied by other automated strategy.
                                It means it can be easily ported without complete workflow escalation process.
                            </td>
                        </tr>
                        <tr>
                            <td class="td_merged">Merged</td>
                            <td class="description_td">Solution is already merged to a release.</td>
                        </tr>
                        <tr>
                            <td class="td_fail">No</td>
                            <td class="description_td">
                                Patch failed to apply.
                            </td>
                        </tr>
                    </tbody>
                </table>

                <table class="result_table legend_table">
                    <thead>
                        <tr class="subheader">
                            <td colspan="3">Release</td>
                            <td>Description</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>2.1.0</td>
                            <td class="td_ok">Ok</td>
                            <td class="td_adaptation_required">No</td>
                            <td class="description_td">Validation was made for the specific release and the results are provided.</td>
                        </tr>
                        <tr>
                            <td colspan="3">2.0.22</td>
                            <td class="description_td">Release is declared in a config, but the corresponding code base is not found or has wrong permissions.</td>
                        </tr>
                        <tr>
                            <td colspan="3">&nbsp;</td>
                            <td class="description_td">Placeholder. Indicates that current group does not have a release corresponding to one defined in other groups.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="footer_div">
        <a target="_blank" href="https://github.com/aabumuslimov/m2_patchchk/blob/master/CHANGELOG.md">Patch Checker Tool ver. 1.6.4</a>
    </div>
</body>
