<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <script type="text/javascript" src="design/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="design/js/jquery/plugins/mfupload.js"></script>
    <script type="text/javascript" src="design/js/uploader.js"></script>

    <link type="text/css" rel="stylesheet" href="design/style/style.css" media="all" />
    <link type="text/css" rel="stylesheet" href="design/style/uploader.css" media="all" />

    <title>Patch check</title>
</head>
<body>
<br />
    <div id="main_content_div">
        <div id="uploader">
            <div id="upload"></div>
            <div id="uploaded"></div>
        </div>
        <div id="results_div" <?php if (isset($result['check_results'])): ?>style="display:block;"<?php endif; ?>>
            <?php foreach($result['check_results'] as $name => $group): ?>
                <table class="result_table">
                    <thead>
                        <td colspan="2"><?php echo $name ?></td>
                    </thead>
                    <tbody>
                        <?php foreach($group as $release): ?>
                            <tr>
                                <?php if ($release['check_result'] === 'n/a'): ?>
                                    <td colspan="3">
                                        <?php echo ($release['release_name'] === 'n/a') ? '&nbsp;' : $release['release_name'] ?>
                                    </td>
                                <?php else: ?>
                                    <td>
                                        <?php echo $release['release_name'] ?>
                                    </td>
                                    <td class="<?php echo ($release['check_result']) ? 'td_ok' : 'td_fail' ?>">
                                        <?php echo ($release['check_result']) ? 'Ok' : 'No' ?>
                                    </td>
                                    <td class="<?php echo ($release['check_git_result']) ? 'td_git_ok' : 'td_git_fail' ?>">
                                        <?php echo ('a') ?>
                                        <?php echo ($release['check_git_result']) ? 'Ok' : 'No' ?>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endforeach; ?>
        </div>

        <div id="message_div">
            <?php echo $messageList ?>
        </div>
    </div>
</body>
